### ISSUE TITLE
disassembly doesnt work and i did everything

### ISSUE THREAD

**Issue by Alex123321op** [sonicretro/skdisasm#43]
Program: SonLVL
Build Date: 12/27/2021 21:10:17
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\DAFO\Desktop\s3diss\Sonic 3K Git INIs\SonLVL.ini"...
Game type is S3K.
Loading Azure Lake...
128x128 chunk file "../Levels/ALZ/Chunks/Primary.bin" not found.
16x16 block file "../Levels/ALZ/Blocks/Primary.bin" not found.
8x8 tile file "../Levels/ALZ/Tiles/Primary.bin" not found.
Layout file "../Levels/ALZ/Layout/1.bin" not found.
Loading palette file "../General/Sprites/Sonic/Palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../General/Sprites/Sonic/Palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Loading Angel Island Zone Act 1 Intro...
8x8 tile file "../Levels/AIZ/Tiles/Act 1 Primary.bin" not found.
128x128 chunk file "../Levels/AIZ/Chunks/Act 1.bin" not found.
16x16 block file "../Levels/AIZ/Blocks/Act 1 Primary.bin" not found.
8x8 tile file "../Levels/AIZ/Tiles/Act 1 Secondary.bin" not found.
Layout file "../Levels/AIZ/Layout/1.bin" not found.
Loading palette file "../General/Sprites/Sonic/Palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
16x16 block file "../Levels/AIZ/Blocks/Act 1 Secondary.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../General/Sprites/Sonic/Palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Loading Angel Island Zone Act 1...
Loading 16x16 blocks from file "../Levels/AIZ/Blocks/Act 1 Primary.bin", using compression Kosinski...
Loading 8x8 tiles from file "../Levels/AIZ/Tiles/Act 1 Primary.bin", using compression KosinskiM...
Loading 128x128 chunks from file "../Levels/AIZ/Chunks/Act 1.bin", using compression Kosinski...
Loading layout from file "../Levels/AIZ/Layout/1.bin", using compression Uncompressed...
Loading 16x16 blocks from file "../Levels/AIZ/Blocks/Act 1 Main Level.bin", using compression Kosinski...
Loading 8x8 tiles from file "../Levels/AIZ/Tiles/Act 1 Main Level.bin", using compression KosinskiM...
Loading palette file "../General/Sprites/Sonic/Palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../General/Sprites/Sonic/Palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Loading Angel Island Zone Act 1 Intro...
Loading 16x16 blocks from file "../Levels/AIZ/Blocks/Act 1 Primary.bin", using compression Kosinski...
Loading 8x8 tiles from file "../Levels/AIZ/Tiles/Act 1 Primary.bin", using compression KosinskiM...
Loading 128x128 chunks from file "../Levels/AIZ/Chunks/Act 1.bin", using compression Kosinski...
Loading layout from file "../Levels/AIZ/Layout/1.bin", using compression Uncompressed...
Loading 16x16 blocks from file "../Levels/AIZ/Blocks/Act 1 Secondary.bin", using compression Kosinski...
Loading 8x8 tiles from file "../Levels/AIZ/Tiles/Act 1 Secondary.bin", using compression KosinskiM...
Loading palette file "../General/Sprites/Sonic/Palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in D:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../General/Sprites/Sonic/Palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in D:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 689
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by TorutheRedFox** [comment]
that's a SonLVL problem
