### ISSUE TITLE
The zone cannot open

### ISSUE THREAD

**Issue by Tails12412** [sonicretro/skdisasm#59]
Program: SonLVL
Build Date: 03/22/2023 18:17:11
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Operating system: Microsoft Windows NT 6.2.9200.0
Opening INI file "C:\Users\Admin\Downloads\SonLVL Updater\Sonic 3K Git INIs\SonLVL - S3.ini"...
Game type is S3K.
Loading Angel Island Zone Act 1 Intro...
8x8 tile file "../Levels/AIZ/Tiles/Act 1 Primary.bin" not found.
16x16 block file "../Levels/AIZ/Blocks/Act 1 Primary.bin" not found.
128x128 chunk file "../Levels/AIZ/Chunks/Act 1.bin" not found.
8x8 tile file "../Levels/AIZ/Tiles/Act 1 Secondary.bin" not found.
16x16 block file "../Levels/AIZ/Blocks/Act 1 Secondary.bin" not found.
Layout file "../Levels/AIZ/Layout/1.bin" not found.
Loading palette file "../General/Sprites/Sonic/Palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../General/Sprites/Sonic/Palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Loading Angel Island Zone Act 1 Intro...
8x8 tile file "../Levels/AIZ/Tiles/Act 1 Primary.bin" not found.
8x8 tile file "../Levels/AIZ/Tiles/Act 1 Secondary.bin" not found.
16x16 block file "../Levels/AIZ/Blocks/Act 1 Primary.bin" not found.
16x16 block file "../Levels/AIZ/Blocks/Act 1 Secondary.bin" not found.
Loading palette file "../General/Sprites/Sonic/Palettes/SonicAndTails.bin"...
Source: 0 Destination: 0 Length: 16
128x128 chunk file "../Levels/AIZ/Chunks/Act 1.bin" not found.
Layout file "../Levels/AIZ/Layout/1.bin" not found.
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at System.Threading.Tasks.Parallel.Invoke(Action[] actions)
   at SonicRetro.SonLVL.API.LevelData.LoadLevel(String levelname, Boolean loadGraphics) in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 184
   at SonicRetro.SonLVL.GUI.MainForm.backgroundLevelLoader_DoWork(Object sender, DoWorkEventArgs e) in C:\Programs\SonLVL\SonLVL\MainForm.cs:line 574
---> (Inner Exception #0) System.IO.FileNotFoundException: Palette file could not be loaded! Have you set up your disassembly properly?
File name: '../General/Sprites/Sonic/Palettes/SonicAndTails.bin'
   at SonicRetro.SonLVL.API.LevelData.LoadLevelPalette() in C:\Programs\SonLVL\SonLVLAPI\LevelData.cs:line 691
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
So this error code show why I cant open a zone

**Comment by Clownacy** [comment]
You're using the wrong INI files: you have to use [the ones in the Sonic & Knuckles disassembly itself](https://github.com/sonicretro/skdisasm/tree/master/SonLVL%20INI%20Files), not the ones that SonLVL Updater downloaded.

**Comment by Tails12412** [comment]
I however followed the son lvl tutorial and then it worked.
